In [1]:
# hw 08 (연산 순서 확인)
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sp
import math
from scipy.spatial.distance import mahalanobis

#np.loadtxt(구분자 : 콤마)
data_a = np.loadtxt("data_a.txt",delimiter=",")
data_b = np.loadtxt("data_b.txt",delimiter=",")

In [2]:
data_a

array([[ 2.9595  ,  1.5581  , -0.61096 , -0.45629 ],
       [ 2.4452  , -0.44842 ,  2.5144  , -0.98481 ],
       [ 3.1157  ,  1.1519  ,  0.063745, -0.7221  ],
       ...,
       [ 3.3099  ,  0.69088 ,  1.2564  , -0.62332 ],
       [ 2.7875  , -0.092662,  2.9127  , -0.11129 ],
       [ 2.9716  , -1.3506  ,  6.8869  ,  1.3202  ]])

In [3]:
data_b

array([[ 3.2407 ,  4.3141 , -2.9888 ,  2.559  ],
       [ 3.048  ,  2.3415 ,  2.0843 ,  3.8624 ],
       [ 2.9453 ,  3.8718 , -3.323  ,  1.3432 ],
       ...,
       [ 2.6321 ,  3.0074 , -1.2821 ,  2.0958 ],
       [ 3.1803 ,  5.943  , -8.3657 ,  0.48498],
       [ 3.0279 ,  2.5626 ,  0.33556,  2.4754 ]])

In [4]:
# PCA구하기(data_a와 data_b를 합함)
# 1. 공분산(Covariance) matrix 구하기
dangdo = np.array([])
density = np.array([])
color = np.array([])
moisture = np.array([])
for i in range(len(data_a)):
    dangdo=np.append(dangdo,[data_a[i][0]])
    density=np.append(density,[data_a[i][1]])
    color=np.append(color,[data_a[i][2]])
    moisture=np.append(moisture,[data_a[i][3]])
for i in range(len(data_b)):
    dangdo=np.append(dangdo,[data_b[i][0]])
    density=np.append(density,[data_b[i][1]])
    color=np.append(color,[data_b[i][2]])
    moisture=np.append(moisture,[data_b[i][3]])    

A_B = np.array([dangdo,density,color,moisture])
A_B
# <초기 data 형태> 
#        당도  밀도  색깔  습도
#사과 1
#사과 2
#사과 3 ... 형태를 아래와 같이 바꿔줌

#당도 : 사과1 사과2 사과3 ...
#밀도 : 사과1 사과2 사과3 ...
#색깔 : 사과1 사과2 사과3 ...
#습도 : 사과1 사과2 사과3 ...  4x1500

array([[ 2.9595  ,  2.4452  ,  3.1157  , ...,  2.6321  ,  3.1803  ,
         3.0279  ],
       [ 1.5581  , -0.44842 ,  1.1519  , ...,  3.0074  ,  5.943   ,
         2.5626  ],
       [-0.61096 ,  2.5144  ,  0.063745, ..., -1.2821  , -8.3657  ,
         0.33556 ],
       [-0.45629 , -0.98481 , -0.7221  , ...,  2.0958  ,  0.48498 ,
         2.4754  ]])

In [5]:
#np.cov : 공분산 matrix를 출력해준다.
A_B_covariance = np.cov(A_B)
A_B_covariance

array([[ 4.65400643e-02,  1.97472057e-02, -7.80869036e-03,
        -5.79295269e-03],
       [ 1.97472057e-02,  5.32460593e+00, -9.54860209e+00,
         1.08606902e+00],
       [-7.80869036e-03, -9.54860209e+00,  1.87863401e+01,
        -3.11847281e-01],
       [-5.79295269e-03,  1.08606902e+00, -3.11847281e-01,
         1.86824703e+00]])

In [6]:
# 2. np.linalg.eig : 공분산 matrix에 대해 eigenvalue(w), eigenvactor(v)를 구한다.
eig_vals, eig_vecs = np.linalg.eig(A_B_covariance)
eig_pairs = [(eig_vals[i],eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs.sort(reverse=True)
# eig_pairs

### PC(Princal Component) : 분산이 가장 넓은 지역
### Covariance Matrix에 있는 Eigen Vector에 해당(n차원에서 n개 존재) Eigen Value가 높은 Eigen Vector를 찾아야 함

# 부분공간 투영 V^-1x
# 이는 아이젠 벡터들과 데이터 간의 행렬곱을 의미

In [7]:
mat_w = np.hstack((eig_pairs[0][1].reshape(4,1),eig_pairs[1][1].reshape(4,1))) #4x2
mat_w.shape
mat_w_T = mat_w.T

In [8]:
pca = np.matmul(mat_w_T,A_B)
pca_T = pca.T

In [9]:
pca_a = pca_T[slice(0,1000)]
pca_b = pca_T[slice(1000,1500)]
pca_a.shape

(1000, 2)

# 가우시안 분포(정규분포)로 모델링
   ## 다변수정규분포
   ## 평균과 covariance를 구하라는 뜻임
   ## 시각화는 추가적인 요소일 뿐임

In [10]:
mu_a = np.array([np.mean(pca_a[:,0]),np.mean(pca_a[:,1])])
mu_b = np.array([np.mean(pca_b[:,0]),np.mean(pca_b[:,1])])
cov_a = np.cov(pca_a.T)
cov_b = np.cov(pca_b.T)

# 올해 수확한 사과 2개체

In [15]:
# test 데이터 부분공간 S에 투영
data_t = np.loadtxt("test.txt",delimiter=",") 
# PCA구하기

# 1. 공분산(Covariance) matrix 구하기
dangdo = np.array([])
density = np.array([])
color = np.array([])
moisture = np.array([])
for i in range(len(data_t)):
    dangdo=np.append(dangdo,[data_t[i][0]])
    density=np.append(density,[data_t[i][1]])
    color=np.append(color,[data_t[i][2]])
    moisture=np.append(moisture,[data_t[i][3]])

T = np.array([dangdo,density,color,moisture])
#np.cov : 공분산 matrix를 출력해준다.
T_covariance = np.cov(T)
T
# <초기 data 형태> 
#        당도  밀도  색깔  습도
#사과 1
#사과 2
#사과 3 ... 형태를 아래와 같이 바꿔줌   2x4

#당도 : 사과1 사과2 사과3 ...
#밀도 : 사과1 사과2 사과3 ...
#색깔 : 사과1 사과2 사과3 ...
#습도 : 사과1 사과2 사과3 ...  4x2

array([[ 0.6322, -4.1113],
       [-3.2764, 10.9427],
       [ 1.6776, -1.157 ],
       [-0.2263, -1.7366]])

In [20]:
pca_tt = np.matmul(mat_w_T,T)
pca_tt.shape
pca_tt

array([[ 3.00594658, -6.00783154],
       [-0.97971413,  1.96355609]])

# Mahalanobis distance

In [26]:
# Mahalanovis Distance 구하기
# a 품종과 test 데이터와의 거리
# (test값 - A의 평균값)
data_At_1 = np.array([[pca_tt[0][0],pca_tt[1][0]]]) - mu_a
# (test값 - A의 평균값)
data_At_2 = np.array([[pca_tt[0][1],pca_tt[1][1]]]) - mu_a 
# C : covariance matrix(a)
C = np.array([[cov_a[0][0],cov_a[0][1]],[cov_a[1][0],cov_a[1][1]]])

C_inv = np.linalg.inv(C)
# Transpose
T_data_At_1 = data_At_1.transpose()
T_data_At_2 = data_At_2.transpose()

MD_At1_First = np.matmul(data_At_1,C_inv)
MD_At1_Result = np.matmul(MD_At1_First,T_data_At_1)

MD_At2_First = np.matmul(data_At_2,C_inv)
MD_At2_Result = np.matmul(MD_At2_First,T_data_At_2)

print('MD_t1 : ',math.sqrt(abs(MD_At1_Result)))
print('MD_t2 : ',math.sqrt(abs(MD_At2_Result)))

MD_t1 :  2.775561925738843
MD_t2 :  6.268366366583433


In [27]:
# Mahalanovis Distance 구하기
# B 품종과 test 데이터와의 거리
# (test값 - B의 평균값)
data_Bt_1 = np.array([[pca_tt[0][0],pca_tt[1][0]]]) - mu_b
# (test값 - B의 평균값)
data_Bt_2 = np.array([[pca_tt[0][1],pca_tt[1][1]]]) - mu_b
# C: 
C = np.array([[cov_b[0][0],cov_b[0][1]],[cov_b[1][0],cov_b[1][1]]])

C_inv = np.linalg.inv(C)
# Transpose
T_data_Bt_1 = data_Bt_1.transpose()
T_data_Bt_2 = data_Bt_2.transpose()

MD_Bt1_First = np.matmul(data_Bt_1,C_inv)
MD_Bt1_Result = np.matmul(MD_Bt1_First,T_data_Bt_1)

MD_Bt2_First = np.matmul(data_Bt_2,C_inv)
MD_Bt2_Result = np.matmul(MD_Bt2_First,T_data_Bt_2)

print('MD_t1 : ',math.sqrt(abs(MD_Bt1_Result)))
print('MD_t2 : ',math.sqrt(abs(MD_Bt2_Result)))

MD_t1 :  5.636964518484305
MD_t2 :  0.5919154583689167
